"""Step 7: build the website into docs/ (GitHub Pages serves this folder).
  docs/index.html  the map: replay of the held-out 2025 and 2026 seasons
  docs/about.html  how it works, where the data comes from, how good it is, limits
Each map day uses ONLY ocean and wind conditions MAP_LEAD days earlier.
Also writes outputs/results.md: the numbers for the report, identical to what the site shows."""
import json, pickle, datetime as dt
import numpy as np, pandas as pd
from config import (INTERIM, OUT, RAW, DOCS, ROOT, END, MAP_LEAD, MAP_SEASON, FEATURES, FEATURE_LABELS,
                    COMMON, DANISH, AT_SEA_MIN_KM, FEATURE_SET, TRAIN_YEARS, TEST_YEARS, GRID_DLAT, GRID_DLON, LEAD_DAYS)
from s02_audit import go_species
from s05_build_dataset import open_env, coast_km, coast_grid, feature_values
import basemap

ALPH = "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz-_"   # 64 levels per cell
TOP_SHARE = 0.20      # "high-likelihood waters" = top 20% of cells that day, within the same distance band

def encode(scores):
    return "".join("." if v < 0 else ALPH[int(round(v * 63))] for v in scores)

def capture(q, band, k):
    """Percentile of cell k among valid cells in the same band (shore / open water) that day."""
    m = (q >= 0) & (band == band[k])
    v = q[m]
    return (np.sum(v < q[k]) + 0.5 * np.sum(v == q[k])) / len(v)

def env_sources():
    log = json.loads((RAW / "env_sources.json").read_text())
    out = {}
    for e in log:
        o = out.setdefault(e["label"], dict(label=e["label"], product=e["product"], dataset_id=e["dataset_id"],
                                            **{"from": e["from"], "to": e["to"]}))
        o["from"], o["to"] = min(o["from"], e["from"]), max(o["to"], e["to"])
    return sorted(out.values(), key=lambda o: o["from"])

def main():
    env = open_env()
    times = pd.Index(env.time.values)
    iy, ix, coast = coast_km(env)
    band = (coast >= AT_SEA_MIN_KM).astype(int)
    kof = {(a, b): k for k, (a, b) in enumerate(zip(iy, ix))}
    lat, lon = env.lat.values, env.lon.values
    end = min(pd.Timestamp(END), times[-1])
    days = {y: [d for d in pd.date_range(f"{y}-{MAP_SEASON[0]}", f"{y}-{MAP_SEASON[1]}")
                if d <= end and (d - pd.Timedelta(days=MAP_LEAD)) in times] for y in TEST_YEARS}
    coast2d = coast_grid(env)
    X = {d: feature_values(env, coast2d, times.get_loc(d - pd.Timedelta(days=MAP_LEAD)), iy, ix, [d] * len(iy), FEATURES)
         for y in days for d in days[y]}
    skill = json.loads((OUT / "skill.json").read_text())
    audit = json.loads((INTERIM / "audit_summary.json").read_text())
    species, results = {}, ["# Results (generated by s07_build_site.py)\n"]
    for sp in go_species():
        tag = sp.replace(" ", "_")
        m = pickle.load(open(OUT / "models" / f"maxent_{tag}_L{MAP_LEAD}.pkl", "rb"))
        obs = pd.read_csv(INTERIM / f"obs_{tag}.csv", parse_dates=["date"])
        obs = obs[obs.date.dt.year.isin(TEST_YEARS)]
        grids, qs, seasons = {}, {}, {}
        for y, dl in days.items():
            enc = []
            for d in dl:
                x = X[d]; ok = x.notnull().all(axis=1).values
                s = np.full(len(x), -1.0); s[ok] = m.predict(x[ok])
                q = np.where(s < 0, -1, np.round(s * 63)).astype(int)
                qs[d] = q; enc.append(encode(s))
            grids[str(y)] = enc
            hits, pct = [], []
            for o in obs[obs.date.dt.year == y].itertuples():
                k = kof.get((o.iy, o.ix))
                if o.date in qs and k is not None and qs[o.date][k] >= 0:
                    p = capture(qs[o.date], band, k); pct.append(p); hits.append(p >= 1 - TOP_SHARE)
            seasons[str(y)] = dict(n=len(hits), hits=int(sum(hits)),
                                   rate=round(float(np.mean(hits)), 3) if hits else None,
                                   mean_pct=round(float(np.mean(pct)), 3) if pct else None)
        sk = skill[sp]
        species[sp] = dict(
            common=COMMON[sp], danish=DANISH[sp], grids=grids, seasons=seasons,
            obs=[[o.date.strftime("%Y-%m-%d"), round(o.decimalLatitude, 4), round(o.decimalLongitude, 4),
                  kof.get((o.iy, o.ix), -1), bool(o.at_sea)] for o in obs.itertuples()],
            skill=sk["rows"], importance=sk["importance"], audit=audit.get(sp))
        r = next(x for x in sk["rows"] if x["lead"] == MAP_LEAD)
        results += [f"\n## {sp} ({COMMON[sp]})\n",
                    f"- Trained on: {r['trained_on']} ({r['n_train_pres']} sighting-days, {TRAIN_YEARS[0]}-{TRAIN_YEARS[-1]})\n",
                    "\n| Days ahead | AUC (95% CI) | Calendar only | Test sightings |\n|---|---|---|---|\n"]
        results += [f"| {x['lead']} | {x['test']['auc']:.2f} ({x['test']['ci'][0]:.2f}-{x['test']['ci'][1]:.2f}) | "
                    f"{x['test']['auc_calendar']:.2f} | {x['test']['n_pres']} |\n" for x in sk["rows"]]
        ow = r["test_open_water"]
        results.append(f"\nOpen-water test sightings (>= {AT_SEA_MIN_KM:g} km from land): {ow['n_pres']}. "
                       + (f"AUC {ow['auc']:.2f}.\n" if "auc" in ow else "Too few to score separately.\n"))
        for y, s in seasons.items():
            if s["n"]:
                results.append(f"- {y} season, {MAP_LEAD} days ahead: {s['hits']} of {s['n']} sightings "
                               f"({s['rate']:.0%}) in the top {TOP_SHARE:.0%} of predicted waters (chance: {TOP_SHARE:.0%}).\n")
    citation = (RAW / "gbif_citation.txt").read_text().splitlines()[0]
    meta = dict(built=dt.date.today().isoformat(), lead=MAP_LEAD, leads=LEAD_DAYS, top_share=TOP_SHARE,
                train_years=[TRAIN_YEARS[0], TRAIN_YEARS[-1]], test_years=TEST_YEARS, season=list(MAP_SEASON),
                at_sea_km=AT_SEA_MIN_KM, grid_km=round(GRID_DLAT * 110.57, 1),
                features=[dict(id=f, label=FEATURE_LABELS[f]) for f in FEATURES],
                citation=citation, env=env_sources(), feature_set=FEATURE_SET,
                selection=json.loads((INTERIM / "feature_selection.json").read_text()))
    full = dict(meta=meta, days={str(y): [d.strftime("%Y-%m-%d") for d in dl] for y, dl in days.items()},
                cells=[[round(float(lat[a]), 4), round(float(lon[b]), 4)] for a, b in zip(iy, ix)],
                coast=[round(float(c), 1) for c in coast], dlat=GRID_DLAT / 2, dlon=GRID_DLON / 2,
                species=species, basemap=basemap.load())
    light = dict(meta=meta, species={sp: {k: v for k, v in s.items() if k not in ("grids", "obs")}
                                     for sp, s in species.items()})
    site = ROOT / "src" / "site"
    for name, payload in (("index.html", full), ("about.html", light)):
        html = (site / name).read_text(encoding="utf-8")
        (DOCS / name).write_text(html.replace("__DATA__", json.dumps(payload, separators=(",", ":"))), encoding="utf-8")
    (DOCS / ".nojekyll").write_text("")
    (OUT / "results.md").write_text("".join(results))
    print("".join(results))
    print("wrote", DOCS / "index.html", "and", DOCS / "about.html")

if __name__ == "__main__":
    main()
